// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJeo1skNgED0Z5qVbJsle5-jYsMi7iJrA',
    appId: '1:314451327268:web:34408c304f384d219c9bb1',
    messagingSenderId: '314451327268',
    projectId: 'flow-funds',
    authDomain: 'flow-funds.firebaseapp.com',
    storageBucket: 'flow-funds.firebasestorage.app',
    measurementId: 'G-705TSQKY4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIZb8hcR7KO_hZiRZnmqKa_11-IqVzVEc',
    appId: '1:314451327268:android:6b7aa2325e9a586c9c9bb1',
    messagingSenderId: '314451327268',
    projectId: 'flow-funds',
    storageBucket: 'flow-funds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Sg4gRF95vN8hTTj73ZQEd6FdcUXX0fw',
    appId: '1:314451327268:ios:f0fd76ec0b5eb3b69c9bb1',
    messagingSenderId: '314451327268',
    projectId: 'flow-funds',
    storageBucket: 'flow-funds.firebasestorage.app',
    iosBundleId: 'com.example.flowFunds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Sg4gRF95vN8hTTj73ZQEd6FdcUXX0fw',
    appId: '1:314451327268:ios:f0fd76ec0b5eb3b69c9bb1',
    messagingSenderId: '314451327268',
    projectId: 'flow-funds',
    storageBucket: 'flow-funds.firebasestorage.app',
    iosBundleId: 'com.example.flowFunds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJeo1skNgED0Z5qVbJsle5-jYsMi7iJrA',
    appId: '1:314451327268:web:31560b505981ba2e9c9bb1',
    messagingSenderId: '314451327268',
    projectId: 'flow-funds',
    authDomain: 'flow-funds.firebaseapp.com',
    storageBucket: 'flow-funds.firebasestorage.app',
    measurementId: 'G-5D31B2KEJ4',
  );

}